package bio.problems

import bio.algorithms.protein.OptimalAlignmentCount
import bio.domain.protein.{OptimalAlignmentCountProblem, ProteinString}
import cats.effect.IO

object CTEAProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("LNLDFMEAQPDMTLLMIAKPVQAGGYRPNGHQGVSPMSPECPFSMTMHMIDLKQHVDEFH\nNTQEKPAWYIFTWQPCSYLAPCADSSMTNPYPTGPGPFTKEGTYTDIRSGANRHTVNWNI\nFYRFWRSIRVRIWEIEYTTMCQVNMKTFTQIARGRYVGRKGMHNNCCTTKMQCSGWHMCP\nSEIPVSEQTDVNEPEAGHDRCSTTGPQRGMWQHMPGVKDTTCTGVFECSRRFSQRHKEMF\nTFKVYCGQMTSGEILFNLDGCSYQTNHHVHRHWASYVECEEKYNFYPSWTWAMAACIIQA\nPPLTFNASQVFCEIRGSVAMNCWMCIAICQSLRYIVDGQPAKCAAFHWFVQPMLCLCYML\nHMCSRPQPRIVTVYMAWDTLSTNKFDGCQCLTGFGFVVPPNHCPNNDKNMEHKHGCWYKI\nICMKFDFMEQASQACMDIDPDSEAWRNKDRLASTWHGYRNMWHIILTADLVVHDLHKGMP\nTYNWHRPATKGMHDSEWHPAMYTYQHKEHEFIHSWKPDMSYIKPKLSAWQIYSTDVAQLR\nALLMTAGCYYGDYIQPPKQAWRGWVYLYNCNLVGPRLNAHNMLFKSAQECHMYSQFLPRT\nQWTFTDKGKDPFATRWWLWYNQTKDSRMHRFTPAMHLRMWGHSDYLIHKFCEGYAEEWPI\nQPFCAQSHNLCSLYDTNKCYRIEDGDEFLAEILKEKCKRYTTNIMATTGEVFDLSRRCMD\nVISGTIYYTMFNPG".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("LNLDMSEAQPDMTLLMIAKPVQALGTRPNGPECPFSMTVRVAQHMINPLKQHVDEFHNTQ\nEKPAWYIFQCWYWQVSFIWQCSYPAPCCDSMMYPSAGPYTDWNWVNWSIFYRFWRSIRVR\nIWEPEYTTMKTFTQIARGYVGRKGMHNACCTGRKMQNDNTCSGWHMCIIPVSYRHHVRCS\nTTGPQDGMWNARAMRGHAMRPFTEPVPGVKDTTCTHVFECSRLFLRGMKGTFSQRLLVYS\nMCLMFTFKVYCGCWCSSGEILYQYWCMCNNLDICGSTGQWCSYNMKKQTEIETDVHNVAH\nHVHEHWATYVECEEKYNFYGYVLSWTNNECPAMAACIIQASPLTFNITTRRMESVAMNCS\nMCIAWPGIMHSSICQGQPAKCAAFHWPINEQPMLCNRDGENCYMLHMCSRPQPRIETFYF\nMCQFDAFDAWDTLSLNKFDGCQCLTGFGFVVPPNMHWANNCKNVEHKGCWYKIICMKFDF\nMEQAQHQACMDIDPDSEAWRNFDRLASTWHGYRNAILVVHDLHKLHSALQKGMHISEWHP\nAMYTYDDCITICRHKPHDLKWEELLFKWRSRWKPIVAQLRAHQMAKLVTAGCYKGDHIQP\nPKQAWRGWVYLGPRDKNIMQPNIFANMLFKSAQVAYNFQPTKAKNRYSPRPFALWYNYHV\nPHLRMWGVYLIHVFDSYHCEGQAMISTRCGDMCAYSHCLCNLYDTNKYDHAYRIEDGDEF\nLAEILKEKCKRYTTNIMATTGEVFDLSESVFRPYNRAPMDELRYIMDVISGTIYTEGNKW\nYTMLNPG".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- OptimalAlignmentCountProblem.from(s, t)
      result = OptimalAlignmentCount.compute(problem)
    } yield result

    r match {
      case Left(err)    => IO.println(s"$err")
      case Right(value) => IO.println(value)
    }
  }
}
