package bio.problems

import bio.algorithms.protein.EditDistance
import bio.domain.protein.{EditDistanceProblem, ProteinString}
import cats.effect.IO

object EDITProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("QFHTYPQGRICEFDDFQKEQQKYFESHCWFWLPYSSPNHAHDMFKYCCLWGWHRQVVEQE\nTVHYLTNDSGHTSSPSCFSEFHGSITPPNLINVWRVMDRSVQDYIKEWMINMHCRMFSED\nQDEILMIWGHQHGCGWNSMWDAMWMHMPPYEEECACIGSFHCSMEMRAIMQLEQCSDSWC\nLQKTQREACLQNPGDCADMQLTRIKVDWYRDMPWDLTDKLKLARDWTCGDAHNFMCAKTL\nSVTRDMFNPEYARDPWMDENMQHKYTHHFDWQVGTDCQFNFAEMQAAFRNRIQFLTSDQE\nEAYSFPKSHSSWTWGCKFDVLHGFSPPRGKHHWVVTPMNDGKRKETMMEKWDAYIKCWSH\nWCMQSGNTGVGMVNTKPEFRAHARHRIPCQPFGRLGIWSWNADHLYAIYFKVFKPHNGPI\nCDEWQSMGWQKSAGEMEEFQETDFEYVFWEWTRWRYWGIYPTNVKNQTCLWASSHHVHVA\nFNKRIREWPKHNNRAKFARPCKEKWMGDSGMSHNKSEHVWGVALYRLGWCVMGEFVQQVH\nGVEQKILIIFWAKGFAHRPYKQNTVIRYAFLVPELSALIWDQRYTKWKNRTIQTKWWSVH\nNLDAGTFWAKAPSGWKPDCGEDPVPEDEMLHLDNCADIYCCRELNAPQKPAYFNGPFWGC\nRSPRFPDYCMHCRNLHLGQALNIYQNGFDDSIMCTHNQELICEYYNNAGFPYYKKVHYWH\nKQRKQEQRDSG".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("QFHTYPQGRICERTDEQQKYFEGHCAHPNYDKWWCMKTLWPAFAHWMFWHRQVREQERVH\nYLTNDSKHFNLFWINTFSEFNGSITPPNDINVWRVMDCFVQVLAWSNPRRYIKESMINCS\nHCRMFKEDQDEILMIWNSMREIHAMWMHMPPYEEECACIGMRAIMQTWFYEQCSDSWCLS\nKCQNPGDCADMQLTRIKVDWYRDMPWWLTDMCKMGHARDWTCTDRAKTLSFNPERIRSPW\nMDENMQHKRASTKRGIKHFDWQVEWCWEAFRNRISPNIKTEEAYSFPKSHQESVDSWTWG\nCKFDNPTLPRGKHHWVVQVWRKVGPMNDGKRKETMMNKWDSENTGVGMVILWDQKPEFRA\nHARFGRLGIWSWNADHLYKPHNGRIDDEWQSMGWQKCAGEMEGMVREEFQETDFEYVFWE\nWTELWRYWGIYPSNQTCLWVHVAFNMRIREWPKHNNVERAKFARPNCTYQSGMSHNKSEH\nVWGVALYRLADWGVRQVHGVEQKLWAKGFAHRPYKQNTVHWYAFLVPIEKITLPDLTLIW\nDQRSMRCTKWKNRTIQTKWWSAHNLWAGTFWEKAPSDCGQDPVFEKEVLETLNDMFSLNR\nADSGNFLKTAQCMDCKIYCCRHCKTKRCSKNAPQKPAYCCMHDRPFGKELYYLHLGSALN\nIIVPTHNFQNGSEDSIMCTHNQELICEYNNNAGFKVAKYWYYKKVHYWHKQRKFEQRDSG".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- EditDistanceProblem.from(s, t)
      result = EditDistance.compute(problem)
    } yield result

    r match {
      case Left(err)    => IO.println(s"$err")
      case Right(value) => IO.println(value)
    }
  }
}
