package bio.problems

import bio.algorithms.protein.EditDistanceAlignment
import bio.domain.protein.{EditDistanceAlignmentProblem, ProteinString}
import cats.effect.IO

object EDTAProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("QWCDNDQEETWRTVATYISWPLEMVEMQHWIASDKQSEMNVNVKHYMLQLTGGPWIMNRM\nMRHPQRHNLEWISYIKDSLDAWKVTTSQQAKCMAFELIQSYMAAHFTLRSGFGRKFLRYH\nSDPSICHESDWDDIAFDQMMLKRPPITKSYYIHTGDGIREHHVITTHLFTWCRFSERNIV\nWHMIVSTIQKTKNMTYAFYAEKEQKDFSWYSGSHDNGGQWTRYSWGGLDTDTGLYIYDPC\nHFYWWHGKFPSLKMCIDDGSHFNHSENPTTNKGAECQTLMRPLTKTWLMCQNSEHCTWAH\nMCQQCMNKFGRFSIYANKFMEDDEKNADHFPQYECCPRKPVACLPYGELSKQCEEETPAV\nQLFTIDSMLQPLDWIPYQFYIYDQSMVHHTFMHIFQKAALIYTKGQDWTSFLGWYQACRV\nPNMRRAWFAFHGGDMFSHDAFIHYFVKLSPRKRWCEGHYEMADMLFKHCHLKYEMQQNRR\nTPTWRHPDYNSMGLHHHFFHWSDSDSCVRVLCDIPWTHKDGFICDPQWSRNCCANLECFV\nCLHYRVIDEYCMPLARFALISFHWNQRKSKPEMGIYQGTPSIFYYFFFSVYQVWQSDQHF\nVFAGGRMMAEMNDCLMTNIQFNFAMYFRRLAHKLLSVTTEKNWAGMTDTQFACQNATLQA\nPGNGQMCYVLMQWHAFHWNKNPTHMNAPLLDLPDSDPPVDDKQMYTGALMMMAFRGETQT\nAFVAPRGMLTYIERFFTQFEDGDGYEPMWQ".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("QWCDNDQLELHNHWNTHNQFYISWPLEMVEMMVRSVKCTHWIASDKQSENKHYFQDMKDL\nQLTGGPWWFWFNRMMRHPQRINLEWISYIKKKSLDCWPPTWAKVTACSQQAKCMAFELIQ\nSYAAAHFTNRSGFGRKFLNWYHESDWDDISFDQMMLCYRPPPGDGIREHHVITGHNTNRF\nSERNIMRPEPAEHMVSTKTYQPDPQVDTAPYAEKEYWDFSFYSMFQWTRYSWDMDMGLYI\nYDPGYFSMWMPAHFYWWHGKFPSLKMGSNPTTNKGAGRMMDWECQTLMRPLTWAHMCQQC\nMWQCRFSIYANKFMEDDEKNADHKCNGPQYFCCPRYKVALPYGLHYSRIDNMVQLKTCDS\nMLQPTDWIPYDDSSLFDFYIYDQSMVHKAALIYTKGQDWLSFLEIYNRFTVWGIMDPFPM\nGQETSYYTWPCFRMCEESPVPNQFAFMGGDMFSHDGFIHYFVKLSPCSLVERKRWCEGTL\nHAWAHWPPDKDTREMADMLFKHCHLKYENQQKRRTPYWMHVDTKCKSLNSMGLHHHFFHW\nSGQIPFQHDEGRVHKDGFICNAQWSRNCCANIECFVCLVISYFTSIEYYWKFFLDMALIS\nFVWNQRSKPEMGQTPSIFYYFFFALENSAVYQVWQMDQHFVRQWATICLMINIAFNFAMR\nFRRPAHKLLSVTTEKNWAGMTDTQTKLYSFLPLQFPGNGYMDIWAGRWHYVLMQWHVLKR\nTQPFHWNKNPQHMNDPLLDYFRYIHQTKDKQMMAFRGETQTRGMLHLSLHKPYIERFFTQ\nFEDGDGYEPMLQ".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- EditDistanceAlignmentProblem.from(s, t)
      result = EditDistanceAlignment.align(problem)
    } yield result

    r match {
      case Left(err) =>
        IO.println(s"$err")
      case Right(alignment) =>
        IO.println(alignment.distance) *>
          IO.println(alignment.augmentedLeft) *>
          IO.println(alignment.augmentedRight)
    }
  }
}
