package bio.problems

import bio.algorithms.protein.ConstantGapAlignmentScore
import bio.domain.protein.{ConstantGapAlignmentScoreProblem, ProteinString}
import cats.effect.IO

object GCONProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("SWRTWFAGIKPALHWNKAWILLYGNQTQVFTGSVSEFAKAIYEPDKGGWYPTEYMDTHAY\nVDENPAPKRDYSKIEYCYGEWNEFDWIMGRELYFYNSNINGGYDDRQHWMKLWEEDWKTM\nFPDCAVALQQYGDAWVMIMEAFWYAQTIPMVEQSYVAGYTHRSYGAATFILMMEICDKIA\nKYDQLIYRFEMAQRSSSLWVYTMRCCHISEPTNVISEWDPLHALDMDSKCLQFVVATPWC\nCNTCYHCWINFMQWEAVSKMTIKHHCDPWRYQMEEEYWPWKATNLKMGVHADGTVWLDKN\nTAWICRYWIELYHLMMDQEKTGTNRWAMMGYKDGFKPKFQSQIMFETGCYDMRHEGSEIV\nDPKFYLYGTQDINMTENNFWPVREWECIYNSVSEGQAPRNVDYYEGCDPQENSLAPMCYF\nMSLRSFKREGPQCQGFCKKRAYGRTCENWFIYKWWLHPRWLQIVNGSHMFYGNKSGVQHL\nNYFMNHCWFNYNWVIVNNLGVAKPWCWGRNWIAMHAFFMFVLELCSIKMKPDVKTSQEYN\nMFDREDSILRFGSWSKYNKTINELVFQANFCGQICYEMKCYYYPEGGVVDSQISANITCG\nSHMWRDEQESEIFWQDRICHKIHDWWDHDLPAMYEGDHLVMRCHMDSNDGATHPQDLSEH\nKMQKYSCGQNILTWSGLMWDPYWEPEHAYCWHFMEHNQITSGLHHYYADGGDEQETEATK\nKHPHLSEGDYSMKFMSYYGFFHQEACGCMYFMVNHWAKCSAMGHPWLLMMLHRGQPSNTD\nHEIPGWRTHGTFLNHPCYQACNGMYPRDNPSDIGWWVVSGVAYCKKCSNKKFFRRDASAT\nSQELWLTILWFNRPSAPDQKLMDC".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("SKKHRLATTGAVAGIVPALEGNQTQAKGFGGWYPTEYMIQTKYKGDENWHLAPKRDYSKI\nEYCYDCILFAEWNEELYCYNSNINGGENSDETDDDQHWMKLWEEDWKTMFPYPSYPDSAV\nALYQYGDSLWVMMLWMEAFWYAIPMVEQSPAGYTHRPYGAATFPLMMEICDQIAKQDQAI\nYREDMAQRKDVGSSLWVYTMRCCHIRRMLEPTKKQDPLHASKCLMMEWCCRTCYWEADSK\nMTWKHHCDPWIYQMEEEYNLKMGVLADGIFRTMNTAWICKFYHLMHDQSQEEKTYTNIFC\nCHVWKDGPSQIMFETWCYDCRHEGSEIVLGPKFYTCGANMGYGPRLEQAQDINMKENNCI\nYDCGCRSFWPEGQQPRNVDYYEGCSLAPMCYFMSLRSFKREKKRAYGWFPMCNGHGHPLS\nEWWIETPRMKKIHPRWLQIVKVRQTGGSHAHPHRMGYKRVGHITYTDGNGVQHLNYFMNP\nGVFKPWCWGRNWIAMHGFFMFVIKMKPDDLCSQMFDREDSSKYTQNKTINELVFQMNFCG\nQICYGPHVGKCYYYLEGGQESDNIDMWDCGSPMRICHKIHDWWGHDLPAMYAMEGDHLVM\nRCHMDSNDGATHPQDLSEHKMQKYSCGQHILTWPFECHCGLMWDPYWAPEHAYCTGDEQE\nTEATKKHPHLFEFPQESNAQDYSMKFVVASQAKLEQPEPYGFFVGCMYFIVNHWAKCSAM\nGHPWLLMMAHRGQPSDNFCPVQTNHEIPGWRTHGTFLNHPCYQACNQMYQFHVIYDNPRD\nIRDWGEKWKCMKEYCKKCSNKKFGYGPRRRDYFQAHFPRMEKKIQKWLTILWFARPSACD\nQKLMDC".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- ConstantGapAlignmentScoreProblem.from(s, t)
      result = ConstantGapAlignmentScore.compute(problem)
    } yield result

    r match {
      case Left(err)    => IO.println(s"$err")
      case Right(value) => IO.println(value)
    }
  }
}
