package bio.problems

import bio.algorithms.protein.GlobalAlignmentScore
import bio.domain.protein.{GlobalAlignmentScoreProblem, ProteinString}
import cats.effect.IO

object GLOBProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("AIISEWRMASAEMDDQQDACNYCVCGYVYCPGASHIYNEGVNIHGAFDLLDTGGISYLFN\nWICRWDNLNWCCGVTTEVYRPKNATKTVPCNNGHKRFNCLCPWIVFMQHCAGMNTPMMNP\nHVDGAAPAWFTHKGKLEKQQAIMCRICPMMKAHVMALCGDKRWIHDKMMWWVGMRIGHLQ\nEIHIHGDDSQQAIERWNCVCGKPNMGHVMTKHLLNVLEHEGGRVEHISWSMIAYWTCDVC\nMHQIRLHRMDIMNSRKSNFGVHIYNGVCDSMELVLLGVPMWQLGYWIDEPQLSYIMLLSG\nSNHIFPFEGSMEGHAYYYKFVWKLPRDGEWHSEMVWMIDVLFIYWYFDIDLSSFLVFKTH\nDKEESLRQEWRDLCPWHWNIIYSFCNKHTGCYGQYIRTSMMYTNVTDRSIDWHYMRRMAE\nVGMLHRFCFWYQNVHWKPWAVLFINQVDTWKMATKSCGFMGYYFHLMGLLPKPIVLFEQE\nQCSEKMLPVVEHPDKTINRPFKEQALYVPRHRFVIEWRNLGARPDCTWCMDHNFETNSVW\nMAGSGVVCGVPLAFFRCMNLQVQLDAWTEDIWYWWKCTYGSGRWQIAQKFVAKKPDQEKH\nHINVEDLDRPWESQFFICAGTTVTCFEEGHVKTLAVHRPDIDTEKFYNSFNSRACNHWWM\nYYTDYMWIGLLHQLDYKLDPYKFHYGWGKEDHVCYMTKFMDLMLYVEVMVVCFISPSGMR\nLDNMNIMSDICPKIIAENQTQKIFAHTFYFGQAGIEGFLNQYIDLEWQPTLGNHGS".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("AIISEFYTTAWRMASAEMDDQQDACYYCVCGYVYCPNSAFLPHSHIYNEGVNIHGAGGIS\nHRWDNLNWCCGVTWEILFPEVYRPKNATPCFNGHKRFNCLCPPIVFMQFCKIIPMNTPMM\nNPHVDGKAPAWILTQCMTHKHTLTRVKQQAIMCRICPKAHVMALCGAKRWIIDKMWWEAH\nIHGYDSQQRWNCVCGYPNMGPMMLKGGRVEHICSMIAYWTCDVCMHQIRMDIMNSRKSNF\nGVHCWHMSTQCYNGVCMPRTWEALLGVEDMWYKDMWQLGYWLGPGAQAFDEPQLSYIAVV\nYNQTLFCQSGSNSVNCWPVWIFPFEGYYYKFVMAIMITMVCMIDYLFIYWYFDIELSSFL\nVFKTHDKEESLRQHQAEWRPWHYNIIYSFLNKHTGCYSQYLRTSMMYTNVTDRSYMRAEV\nGMEFLHFWYQNVHWKPAVLFINQVDNCPHRWKMATKDLCFRKRGFMGYYPSWFHLMCQVA\nLLGWQEQDSEKMHKCAKKAEHPDKTINRPFKEQALYVPRHMTVSRPVKYFVIEWREGGRP\nDCHNFVCNSWNAGKGVVCGVPLAFFVCMHHDYRLQLDAWTEDIWGGDKCTYGSFRWQIAC\nDLPKFVAKKPDQEKHHINEDLDSMFQLNICAGTRKTEFAVTCFEEGHPMLVDESCKFATI\nDDTSSATTDIDTFYTSFHTNVKSFYNNMFIWGMYTDYMWIGERPYNMVKWHQLDNIQTGK\nEMDHMLYVEVDVVYFISPSGMRLDNMNIMRYDVRWIMDICPKIIIENFSWHIMTRTQKYF\nAHTGIEGFLNQHIDLWYPLTCCQHLGNHGS".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- GlobalAlignmentScoreProblem.from(s, t)
      result = GlobalAlignmentScore.compute(problem)
    } yield result

    r match {
      case Left(err)    => IO.println(s"$err")
      case Right(value) => IO.println(value)
    }
  }
}
