package bio.problems

import bio.algorithms.protein.LocalAlignment
import bio.domain.protein.{LocalAlignmentProblem, ProteinString}
import cats.effect.IO

object LOCAProb {

  def solve(): IO[Unit] = {

    val s = ProteinString
      .from("VLKTKREEKFVCRYFNWGTKNVHGDQSWAKLGKCELYPPDYVGYHYSQHPIWGKDQHTKC\nSFQEKIINHEMGIVRYHIANKIDRYNCYDNQVQGSIDWKQKDWFRNVQYNLKVNDYGCWD\nTQYRKRPEVVHWSCFIKQEQCKNACDYRARHALNLEEFQYPSNQMMQIMDPMFFLVCKEH\nCTHDDFGPQWWHSAQPHELFTNWHAWCIWGNNFHVGKYVSIMIQFWTMGNRTHDASLEQN\nNMIMMPQQMQHYQQNQFEHAPTPTDMKEDYIYKNMYDPNAINIILKKCQCLRPWAYTMIY\nGIMNCGPGREPNIWCHFLPCGWGKCVGMNHGEMKYDLWPPIYLTRSDLQICRAYYVWDEL\nNAIHPWSGDVFHNCQALVCALRTGRFWRWQANYLVAQNHDFEETMADWICRYHIQENGGK\nTAVPDRAAKDHQNFFTGTLAPCTMYVNLSPWGMADVLMTKRCKKALGNYLNIVKCMLDEY\nGGTKHRPSWGFREFPEAYYMMAYIAFDFKGHTQMANETYWAHLPLCPRLQAWHRREDSCV\nSHCFSPYFMTGVISGHKGMPAGQWCMLDQNPMRKHMPLEGKAAKLFQINYDWSMPCVRFI\nKTSHLHMFSVKKEMMLSMAKCGSELCKTCHPKIEFCFRTKIGWVMMYSFKTATVESHSKP\nKGICDMLCMHVTNMLSGSWLMCKQMRHCVALLIKRTREFVCRNGWGMYGLPEWKHMEWRW\nLMNFHMDRKCICGNILMEAINSDKMRDYYQLVLVINMDQDPNGLFRDDHEEQAWKRMPKW\nYWNRIFQIRNHEKRLRSFKTFFMSKHASMSIAWYHDNSGHAYCRVVAMGNQWQYHGTVWH\nDIMNSDYVFFMGDWMYRKWKRQWVPMTRIEEKKYLEWGEELASIRIMRDKWSMIEDWFNL".replace("\n", ""))
      .getOrElse(sys.error("invalid left protein string"))
    val t = ProteinString
      .from("TDIWIACNWLCCGRPHRPCFDDVLGWMPALPELWCYNGNAACHRLGAGTEAQEMYNIAMS\nDLIAVMNVLRVNAKNPGCEGITAVHEDWVLAMCYYSNECRLICGISFLSQIGFYPQWWNG\nNMPRMSNIMNASSGKAVRPSYRWPICDDSKSWDNDEQDRWTAFRGRRSMWTYMKENRDHE\nCRWIDDIFFVIIYLLVKWWFPAAQKHLRIRLWRAGNSKEFMETGPLFYLFRNDDMVVMVP\nPQAQCWWHIHVFPNWEYCKRDFNVMLVFLIDWDVPNGCKVYDPKMMFYDAHDMFYPWPLT\nTIYGIMNCWIVDDEHPLPCFGTAIALFCGKCVFLWNPGEMKYDLTRSDDQICRAYYVWDE\nLNAIHPWSGDVFHNCQALVSACRTGRYLVAQNDYNWPWIGSRRYHIIQWDAFNYAENGGK\nTAVPDCHGTLAPCTMYVNGMYLHHQNFPPWGMADENQQNYDSVKCGHTFMLDIYHQTKHR\nPSWMYFREFPEAYYMMAYIAMANYLPLCPREHVKMRLQAWREFYPTGMDQVYPHSGHKGR\nTCILNPMRKHMPLEGKKAKLVIIIKMRDSYDWSMPCVRFKDNVHIKTSHTHMFSVKKEMG\nSEMCKTCHPAYIEFCFRTKIIGWTMMYSLRTATVESHSSEMSAACPYGKECSPLDTLDSG\nQKGLHCGMIKNFHNPFNYIETCQVGCLIKRQRLGFVIINLGGFQHARPTDQNYSFCQHGK\nMFLEQWSYFAPCSCFEITGENAQQWFWKHRALAAYWWNRKIIGMWSCAKVWNSCDLTQCD\nITPFTDADTRCSRHHFNTMVYRKLTMHFHIYRYREWYHSVVPRMVLMYKERHMKTGKVMM\nQLNCYACWIMGLESATCIIHATRAPAPQAPQKKLHESDFGKVTPSAKTVGTCTHYQPCHT\nKGWT".replace("\n", ""))
      .getOrElse(sys.error("invalid right protein string"))

    val r = for {
      problem <- LocalAlignmentProblem.from(s, t)
      result = LocalAlignment.compute(problem)
    } yield result

    r match {
      case Left(err) =>
        IO.println(s"$err")
      case Right(alignment) =>
        IO.println(alignment.score) *>
          IO.println(alignment.leftSubstring) *>
          IO.println(alignment.rightSubstring)
    }
  }
}
