package bio.problems

import bio.algorithms.analysis.IsolatedSymbols
import bio.domain.analysis.IsolatedSymbolsProblem
import bio.domain.nucleic.DnaString
import cats.effect.IO

object OSYMProb {

  def solve(): IO[Unit] = {

    val s = DnaString
      .from("AACAATAGTCCACGTTTGCTCGCGAATCGACGCAAGCTATTGCTCGCACCATCCCGTCGG\nTTATTTTGTGCGCCAGTAAATCGTCACAATCAACTAGGCAACAGGGTATTCAGCATACTC\nTCGATTACCTTAAGTTTGGCGTTCAGAGACCGTCCTCGAATATGGAGGATTACTTCCATC\nCATAACAACAGCAGGGCTCTCGAACTCTACGGTCGAGTACGTTCGTACCCAATGTATCAG\nTTGGACATCGGCGACGCCCCTGTCCTCGCCCAATACCCACAGTCGTGAGGTCAGTCCAGG\nGTTACGGTCGGAGTCAAATAACGAGGGTGGAAGAACGCCAGCCTAGAATACGCTCATATA\nATGTTCCAGATCGGTCCATATGAGCGCACGGGTAAGAGTAAGTTGGACAATGCCTAGGTG\nTGATGCCACTTTCTTGCCCCTTTCATGTGCGCTACCTCGAGCTCACTCCATTTATCAGGC\nCTGCTGGGAGGGGATCCTGTCCGGAACGGCGATCCCGCTCCCAAACGTAGCTGGTCCAAT\nTCTCCAATAGAGCTACACAGACAACACATAATCACAACCGGTCAACTAGAACAACGACCC\nCTTAGGTGTACTTACATAACACAAGACATAGGTGTCTTTGGTGAAATTAAACCTGTGAGC\nCGTCATCGCAAGCGGATGAGTCGCATCAACAGAGCATCGGCTGCTCCTCCGAGTTGAGGG\nCCTCCAGAGGCTATAGGTCTAGGCTATTTAACCATTGATCCCATGCAAAACATAGCTCTT\nAGCAAGTAGTAACTAGCGGAGATTGTCCTCAAGCTGAGGCTCGCCGTAGGGGGCGTAGAC\nGTTTTACGGCGCTCATACAGGTAAATAGTACGGCGAGGGGACCCTCGATGTGAGCAGCAA\nCAGGTCTCCGGCATAGAGGAGCACCTGTTGACGATGGCTCGTGCGGAGGTCAATCGGGGC\nGTGCTCCTATTCATCGTTAGGTTTG".replace("\n", ""))
      .getOrElse(sys.error("invalid left DNA string"))
    val t = DnaString
      .from("TCGGGCTCTCCGATACCTCATCACCTGGTAGCTACCTAATCCAGACGCGCGCATATTACT\nAGACCATGCACCAGCTCACTCTGGTGACTCTCAGAATTTAGGTGTGTCAGCATTGCTACT\nTGGTAGTAGAGACATCCCTTCCCCCTATAATAAATGGACGAACCTAGAGAGATGCATGCG\nGTGTTAAGCATGCCTTAGTGTACACAGTTACACGTACGAGGGTAATCGCGTTCAGAGTAA\nCACTGAACCGGTTGCCTTGCTTTATGGGGTGCCCTTTCGGCCTACCGTAGGCGTGGTGCA\nCGGGAATAGAGCGTCCGTTATGCGGAAGGTACTGGGTACCCTTAATGCCATTGATGGAGC\nGTCACCTAAACTCTGATCACCTCAAAGGTTCAAGCTCTTCCGCAGTCGTCATACACTTCG\nACGGAAATCGTGGCTCCTCCCGCTTAAAGTATGAGTTGTTAAGCGCGGCGATTAGCTCAC\nCAAGTAACGATGTCATCTTGTCGGACTGATATCAAATAATAATACTGTAGCCCCAAGCGT\nGCGCAGCAATTCCTGCTTCAATTTGTGGCACGACAGGGTTTTTATCGTCGCAAGATGACC\nGGGCTGGGCTCTCGGCGTGCGTGTCAGAAGATCTTGAATGCATTCGAAGAAGGACGTGTA\nGAATTCTTCACCACCGTAGGAGGCGTCGTCGCATCCTCAGAAGCTGGTTACACCATGATA\nTTATCTATCTGCACCTACATGTAGCGCCCGATGATAATACTCGTGGGTCCTACGGGGCGG\nCAACTGAATTTAGTCGGTTTCATTTTTAACCCCGAG".replace("\n", ""))
      .getOrElse(sys.error("invalid right DNA string"))

    val r = for {
      problem <- IsolatedSymbolsProblem.from(s, t)
      result = IsolatedSymbols.compute(problem)
    } yield result

    r match {
      case Left(err) =>
        IO.println(s"$err")
      case Right(isolated) =>
        IO.println(isolated.globalScore) *>
          IO.println(isolated.matrixSum)
    }
  }
}
