package bio.problems

import bio.algorithms.analysis.SplicedMotif
import bio.domain.analysis.SplicedMotifProblem
import bio.domain.nucleic.DnaString
import cats.effect.IO

object SSEQProb {

  def solve(): IO[Unit] = {

    val s = DnaString.unsafeFrom("ATGTAGCATAGGCTTTTGTGTAATCTAAGCTCGGCTACCGATGTGGAGTCTAAGAGAAACGTACTGCCAGCAACCGTGATTGCGCTGACGTACACACGCCGATGTCCCTGAACCTAAAGGCATCTCGACCAACCGATCTTCACCGAATATAACACAAACGCCGGCACGTGCAGGTCCGAGGAGCAGTGGTCTCGCTTGAATAAGCGTTGTCGATATTCAGGTCTAGGAGAATGCCAATTCAGACTCGACTAGCATTACGGCCGATACTTGCAACGGACGTCACTGCCTTGTACGATGGCACGTCCCGCTGCGGGTCCGTCGGACCCGTGTGCCACTGTCCGTCTGTCTACGCTGCAATCC\nATTCCGGGTGATTCTAGCAGGGAGCAGGACTCTGAAATTTCTGGGGTCAGGGTTGAATAAAGATGAAAGTCGAGACGGCTTGGACCAGGGTGATTCTGCCTAGTTGGTCTCCTGGCGCGTTTATGAAATAACAGTCCCAAGCTACATGAGGGGCCATAGCATCCATATTCCCTTATGAGTGATGACCAATAGTAGTTGGTAGCGCCTTAGAATAAATGATATAGTAGCGTGCGCAAGATGCCCCCTGGTTTGGCCAGACCAGATGAAGAAGAACCTAGGCTTTACTAACACGGACTGTTCTCTGGAGGACCAGGCTCTCTCCTCTCTTCGCCGCTGGAGCTAAATATGGGTGGAACGCCGGTTCCGCGAAACGAGCGCAAATGCAACCTCGTTAGAATGGACCGCGATTCACTATTTGTCGTAAAATTTTCGTAAATCTTCCGT")
    val t = DnaString.unsafeFrom("AGGACGTTGAGTTATTG")

    val maybeResult = for {
      problem <- SplicedMotifProblem.from(s, t)
      result = SplicedMotif.find(problem)
    } yield result

   maybeResult match {
     case Left(err) => IO.println(s"${err}")
     case Right(maybeVector) =>
       maybeVector match {
         case Some(vector) =>
           val out = vector.foldLeft("")((acc, v) => acc ++ s"${v.toString} ")
           IO.println(out)
         case None => IO.println("no data")
       }
   }
  }

}
